id: AC0AE519B
title: A Prayer to Kyabje Dilgo Khyentse Rinpoche
type: translation
pechas:
- I15470CCD
- I15BEBEEC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:38:00.763062
  last_modified_at: 2023-01-04 11:38:00.763076
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I15470CCD/EE23: 491C
  I15BEBEEC/A4C9: 491C
